# Generated by Django 4.2.8 on 2025-11-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_format',
            field=models.CharField(choices=[('date_month_year', 'Date Month Year'), ('month_year', 'Month Year'), ('quarter_year', 'Quarter Year'), ('year', 'Year')], default='date_month_year', help_text='Date format for displaying publication date', max_length=20),
        ),
    ]
