# Generated by Django 4.2.8 on 2025-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_update_book_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['shelf', 'title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title (required)', max_length=255),
        ),
    ]
