# Generated by Django 4.2.8 on 2025-11-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_alter_shelf_unique_together'),
        ('books', '0003_alter_book_options_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, help_text='Shelf where book is stored (null means in storage)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shelves.shelf'),
        ),
    ]
