# Generated by Django 4.2.8 on 2025-11-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0004_alter_shelf_unique_together'),
        ('books', '0004_alter_book_options_alter_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('storage', 'Storage - Not on any shelf'), ('library', 'Library - On shelf'), ('borrowed', 'Borrowed - User borrowed')], default='storage', help_text='Book status/location', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, help_text='Shelf where book is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shelves.shelf'),
        ),
    ]
