# Generated by Django 4.2.8 on 2025-11-14 18:52

from django.db import migrations, models
from datetime import date


def convert_year_to_date(apps, schema_editor):
    """Convert integer year values to dates (Jan 1 of that year)."""
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.exclude(year__isnull=True):
        try:
            # Convert year integer to date (Jan 1 of that year)
            book.year = date(int(book.year), 1, 1)
            book.save()
        except (ValueError, TypeError):
            # If conversion fails, set to None
            book.year = None
            book.save()


def reverse_convert(apps, schema_editor):
    """Reverse the conversion (not applicable for DateField)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_borrow_date_book_borrowed_by_user'),
    ]

    operations = [
        migrations.RunPython(convert_year_to_date, reverse_convert),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, help_text='Publication date', null=True),
        ),
    ]
