# Generated by Django 4.2.8 on 2025-11-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookshelves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Shelf name (optional)', max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, help_text='Brief description shown on cards', max_length=255)),
                ('long_description', models.TextField(blank=True, help_text='Detailed description shown in detail view')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='bookshelves.bookshelf')),
            ],
            options={
                'ordering': ['bookshelf', 'order', 'created_at'],
            },
        ),
    ]
