# Generated by Django 4.2.8 on 2025-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description shown in detail view'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description shown on cards', max_length=255),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(blank=True, help_text='Shelf name (optional)', max_length=255, null=True),
        ),
    ]
